// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projet.Models;

#nullable disable

namespace Projet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240222022000_BDProjet")]
    partial class BDProjet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Projet.Models.Enfant", b =>
                {
                    b.Property<int>("EnfantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnfantId"), 1L, 1);

                    b.Property<int>("AnneeProduction")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("IdParent")
                        .HasColumnType("int");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EnfantId");

                    b.HasIndex("IdParent");

                    b.ToTable("Enfants");

                    b.HasData(
                        new
                        {
                            EnfantId = 1,
                            AnneeProduction = 2005,
                            Description = "Avion monomoteur léger.",
                            IdParent = 1,
                            ImageFileName = "cessna 172 1.png",
                            Nom = "Cessna 172",
                            Prix = 100000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 2,
                            AnneeProduction = 2002,
                            Description = "Avion monomoteur léger.",
                            IdParent = 1,
                            ImageFileName = "cessna 152 2.png",
                            Nom = "Cessna 152",
                            Prix = 80000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 3,
                            AnneeProduction = 2008,
                            Description = "Avion monomoteur à pistons.",
                            IdParent = 1,
                            ImageFileName = "CESSNA 182 1.png",
                            Nom = "Cessna 182",
                            Prix = 120000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 4,
                            AnneeProduction = 2015,
                            Description = "Jet d'affaires léger à réaction.",
                            IdParent = 1,
                            ImageFileName = "Carravan.png",
                            Nom = "Cessna Citation",
                            Prix = 500000m,
                            Type = "Jet"
                        },
                        new
                        {
                            EnfantId = 5,
                            AnneeProduction = 2010,
                            Description = "Avion léger à quatre places.",
                            IdParent = 2,
                            ImageFileName = "Archer 1.png",
                            Nom = "Piper Archer",
                            Prix = 90000m,
                            Type = "Léger"
                        },
                        new
                        {
                            EnfantId = 6,
                            AnneeProduction = 2007,
                            Description = "Avion monomoteur à ailes hautes.",
                            IdParent = 2,
                            ImageFileName = "CHEROKEE 1.png",
                            Nom = "Piper Cherokee",
                            Prix = 75000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 7,
                            AnneeProduction = 2009,
                            Description = "Avion léger de sport.",
                            IdParent = 2,
                            ImageFileName = "PIPER PA24.png",
                            Nom = "Piper PA24",
                            Prix = 80000m,
                            Type = "Léger"
                        },
                        new
                        {
                            EnfantId = 8,
                            AnneeProduction = 2012,
                            Description = "Avion monomoteur léger et rapide.",
                            IdParent = 2,
                            ImageFileName = "piper pa28.png",
                            Nom = "Piper PA28",
                            Prix = 100000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 9,
                            AnneeProduction = 2018,
                            Description = "Jet d'affaires monoréacteur.",
                            IdParent = 3,
                            ImageFileName = "SR22T 1.png",
                            Nom = "Cirrus SR22T",
                            Prix = 600000m,
                            Type = "Jet"
                        },
                        new
                        {
                            EnfantId = 10,
                            AnneeProduction = 2015,
                            Description = "Avion monomoteur à pistons de haute performance.",
                            IdParent = 3,
                            ImageFileName = "SR22 1.png",
                            Nom = "Cirrus SR22",
                            Prix = 300000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 11,
                            AnneeProduction = 2013,
                            Description = "Avion à réaction légère.",
                            IdParent = 3,
                            ImageFileName = "SR20 1.png",
                            Nom = "Cirrus SR20",
                            Prix = 200000m,
                            Type = "Monomoteur"
                        },
                        new
                        {
                            EnfantId = 12,
                            AnneeProduction = 2020,
                            Description = "Jet monomoteur à réaction de type Vision Jet.",
                            IdParent = 3,
                            ImageFileName = "VISON JET 1.png",
                            Nom = "Cirrus Vision Jet",
                            Prix = 1000000m,
                            Type = "Jet"
                        });
                });

            modelBuilder.Entity("Projet.Models.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ParentId");

                    b.ToTable("Parents");

                    b.HasData(
                        new
                        {
                            ParentId = 1,
                            Description = "Description du CESSNA",
                            ImageFileName = "CESSNA.png",
                            Nom = "CESSNA"
                        },
                        new
                        {
                            ParentId = 2,
                            Description = "Description du PIPER",
                            ImageFileName = "PIPER.png",
                            Nom = "PIPER"
                        },
                        new
                        {
                            ParentId = 3,
                            Description = "Description du CIRRUS",
                            ImageFileName = "CIRRUS.png",
                            Nom = "CIRRUS"
                        });
                });

            modelBuilder.Entity("Projet.Models.Enfant", b =>
                {
                    b.HasOne("Projet.Models.Parent", "Parent")
                        .WithMany("Enfants")
                        .HasForeignKey("IdParent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Projet.Models.Parent", b =>
                {
                    b.Navigation("Enfants");
                });
#pragma warning restore 612, 618
        }
    }
}
